apiVersion: v1
kind: Service
metadata:
  name: dockerj
  labels:
    app: dockerj
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30121
  selector:
    app: dockerj
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerj
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dockerj
        tier: frontend
    spec:
      containers:
      - name: dockerj
        image: registry.ng.bluemix.net/spaceu/dockerj:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /opt/service-bind
            name: service-bind-volume
      volumes:
        - name: service-bind-volume
          secret:
            defaultMode: 422
            secretName: binding-app1
